apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: releases.app.alauda.io
spec:
  group: app.alauda.io
  version: v1alpha1
  names:
    kind: Release
    listKind: ReleaseList
    plural: releases
    singular: release
    shortNames:
      - rel
  scope: Namespaced
  additionalPrinterColumns:
    - name: Status
      type: string
      description: Status of this Release
      JSONPath: .status.status
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp