apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  labels:
    app: captain
  name: captain-serving-cert
  namespace: alauda-system
spec:
  commonName: captain.alauda-system.svc
  dnsNames:
    - captain.alauda-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: captain-selfsigned-issuer
  secretName: captain-webhook-cert