apiVersion: v1
kind: Service
metadata:
  name: captain
  namespace: alauda-system
spec:
  ports:
    - port: 443
      name: webhook
      targetPort: 443
    - port: 6060
      name: metrics
      targetPort: 6060
  selector:
    service_name: captain